const products = [
  { id: 1, name: "Dreams", price: 23, img: "./image/0.jpg", count: 1 },
  { id: 2, name: "Chosen Ones", price: 35, img: "./image/1.jpg", count: 1 },
  { id: 3, name: "Matter of Time", price: 43, img: "./image/2.jpg", count: 1 },
  { id: 4, name: "Letter to Self", price: 45, img: "./image/3.jpg", count: 1 },
  { id: 5, name: "Born to Be", price: 20, img: "./image/4.jpg", count: 1 },
  { id: 6, name: "Sequence", price: 19, img: "./image/5.jpg", count: 1 },
  { id: 7, name: "The Vibes", price: 15, img: "./image/6.jpg", count: 1 },
  { id: 8, name: "American Dream", price: 28, img: "./image/7.jpg", count: 1 },
  { id: 9, name: "Breathe In", price: 40, img: "./image/8.jpg", count: 1 },
  { id: 10, name: "Iechyd Da", price: 36, img: "./image/9.jpg", count: 1 },
  { id: 11, name: "Rolling Stone", price: 52, img: "./image/10.png", count: 1 },
  { id: 12, name: "Obsidian", price: 10, img: "./image/11.png", count: 1 },
  { id: 13, name: "Orquídeas", price: 12, img: "./image/12.jpg", count: 1 },
  { id: 14, name: "Insano", price: 25, img: "./image/13.jpg", count: 1 },
  { id: 15, name: "Big Sigh", price: 29, img: "./image/14.jpg", count: 1 },
  { id: 16, name: "Lovegaze", price: 16, img: "./image/15.png", count: 1 },
  { id: 17, name: "DOA", price: 55, img: "./image/16.png", count: 1 },
  { id: 18, name: "Jahanam", price: 55, img: "./image/17.jpg", count: 1 },
  { id: 19, name: "Sheytan", price: 60, img: "./image/18.jpg", count: 1 },
  { id: 20, name: "Album 87", price: 98, img: "./image/19.jpg", count: 1 },
  { id: 21, name: "BOHT", price: 110, img: "./image/20.jpg", count: 1 },
  { id: 22, name: "Zir 8", price: 12, img: "./image/21.jpg", count: 1 },
  { id: 23, name: "SAHM", price: 19, img: "./image/22.jpg", count: 1 },
  { id: 24, name: "CosMos", price: 16, img: "./image/23.jpg", count: 1 },
];
